import express from 'express'; import cors from 'cors'; import helmet from 'helmet'; import morgan from 'morgan'; import bcrypt from 'bcryptjs'; import { z } from 'zod'; import dotenv from 'dotenv'; import { pool, tx } from './db.js'; import { auth, signToken } from './auth.js';
dotenv.config();
const app=express(); app.use(helmet()); app.use(cors({origin:process.env.CLIENT_URL||'http://localhost:5173'})); app.use(express.json()); app.use(morgan('dev'));
const port=Number(process.env.PORT||5000);
const publicUser=(u:any)=>({id:u.id,name:u.name,email:u.email,level:u.level,xp:Number(u.xp),gold:u.gold,strength:u.strength,wisdom:u.wisdom,intellect:u.intellect,spirit:u.spirit,currentStreak:u.current_streak,bestStreak:u.best_streak,theme:u.theme});
const authSchema=z.object({email:z.string().email(),password:z.string().min(6)});
app.get('/api/health',(_,res)=>res.json({ok:true}));
app.post('/api/auth/register',async(req,res)=>{try{const {name,email,password}=z.object({name:z.string().min(2).max(80),...authSchema.shape}).parse(req.body);const hash=await bcrypt.hash(password,12);const r=await pool.query('INSERT INTO users(name,email,password_hash) VALUES($1,$2,$3) RETURNING *',[name,email.toLowerCase(),hash]);res.status(201).json({token:signToken(r.rows[0].id),user:publicUser(r.rows[0])})}catch(e:any){res.status(e.code==='23505'?409:400).json({message:e.code==='23505'?'Email already registered':'Invalid registration data'})}});
app.post('/api/auth/login',async(req,res)=>{try{const {email,password}=authSchema.parse(req.body);const r=await pool.query('SELECT * FROM users WHERE email=$1',[email.toLowerCase()]);if(!r.rowCount||!(await bcrypt.compare(password,r.rows[0].password_hash)))return res.status(401).json({message:'Invalid email or password'});res.json({token:signToken(r.rows[0].id),user:publicUser(r.rows[0])})}catch{res.status(400).json({message:'Invalid login data'})}});
app.get('/api/me',auth,async(req,res)=>{const r=await pool.query('SELECT * FROM users WHERE id=$1',[req.userId]);if(!r.rowCount)return res.status(404).json({message:'User not found'});res.json({user:publicUser(r.rows[0])})});
app.get('/api/dashboard',auth,async(req,res)=>{const [u,q,a]=await Promise.all([pool.query('SELECT * FROM users WHERE id=$1',[req.userId]),pool.query('SELECT * FROM quests WHERE user_id=$1 ORDER BY completed,created_at DESC LIMIT 20',[req.userId]),pool.query('SELECT * FROM activity_log WHERE user_id=$1 ORDER BY created_at DESC LIMIT 12',[req.userId])]);res.json({user:publicUser(u.rows[0]),quests:q.rows,activity:a.rows});});
const questSchema=z.object({title:z.string().min(1).max(160),description:z.string().max(1000).optional(),category:z.string().default('Discipline'),difficulty:z.enum(['Easy','Normal','Hard','Epic']).default('Normal'),xpReward:z.number().int().positive().max(10000).default(100),goldReward:z.number().int().min(0).max(10000).default(30),attribute:z.enum(['strength','wisdom','intellect','spirit']).default('wisdom'),frequency:z.enum(['Daily','Weekly','Once']).default('Daily'),dueDate:z.string().optional()});
app.get('/api/quests',auth,async(req,res)=>{const r=await pool.query('SELECT * FROM quests WHERE user_id=$1 ORDER BY completed,created_at DESC',[req.userId]);res.json({quests:r.rows})});
app.post('/api/quests',auth,async(req,res)=>{try{const q=questSchema.parse(req.body);const r=await pool.query(`INSERT INTO quests(user_id,title,description,category,difficulty,xp_reward,gold_reward,attribute,frequency,due_date) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[req.userId,q.title,q.description||'',q.category,q.difficulty,q.xpReward,q.goldReward,q.attribute,q.frequency,q.dueDate||null]);await pool.query('INSERT INTO activity_log(user_id,type,message,metadata) VALUES($1,$2,$3,$4)',[req.userId,'QUEST_CREATED',`Created quest: ${q.title}`,JSON.stringify({questId:r.rows[0].id})]);res.status(201).json({quest:r.rows[0]})}catch{res.status(400).json({message:'Invalid quest'})}});
app.put('/api/quests/:id',auth,async(req,res)=>{try{const q=questSchema.partial().parse(req.body);const r=await pool.query(`UPDATE quests SET title=COALESCE($1,title),description=COALESCE($2,description),category=COALESCE($3,category),difficulty=COALESCE($4,difficulty),xp_reward=COALESCE($5,xp_reward),gold_reward=COALESCE($6,gold_reward),attribute=COALESCE($7,attribute),frequency=COALESCE($8,frequency),due_date=COALESCE($9,due_date),updated_at=NOW() WHERE id=$10 AND user_id=$11 RETURNING *`,[q.title,q.description,q.category,q.difficulty,q.xpReward,q.goldReward,q.attribute,q.frequency,q.dueDate||null,req.params.id,req.userId]);if(!r.rowCount)return res.status(404).json({message:'Quest not found'});res.json({quest:r.rows[0]})}catch{res.status(400).json({message:'Invalid quest update'})}});
app.delete('/api/quests/:id',auth,async(req,res)=>{const r=await pool.query('DELETE FROM quests WHERE id=$1 AND user_id=$2 RETURNING title',[req.params.id,req.userId]);if(!r.rowCount)return res.status(404).json({message:'Quest not found'});res.json({ok:true})});
app.post('/api/quests/:id/complete',auth,async(req,res)=>{try{const result=await tx(async c=>{const qr=await c.query('SELECT * FROM quests WHERE id=$1 AND user_id=$2 FOR UPDATE',[req.params.id,req.userId]);if(!qr.rowCount)throw Object.assign(new Error('Quest not found'),{status:404});const q=qr.rows[0];if(q.completed)throw Object.assign(new Error('Quest already completed'),{status:409});const ur=await c.query('SELECT * FROM users WHERE id=$1 FOR UPDATE',[req.userId]);const u=ur.rows[0];let xp=Number(u.xp)+q.xp_reward,level=u.level,gold=u.gold+q.gold_reward;let leveled=false;while(xp>=100*Math.pow(level+1,2)){level++;leveled=true;}
const attr=q.attribute;const allowed=['strength','wisdom','intellect','spirit'];const attrInc=allowed.includes(attr)?1:0;const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);const today=new Date().toISOString().slice(0,10);let streak=u.current_streak;if(u.last_quest_date?.toISOString?.().slice(0,10)===today){}else if(u.last_quest_date?.toISOString?.().slice(0,10)===yesterday)streak++;else streak=1;const best=Math.max(streak,u.best_streak);await c.query(`UPDATE users SET xp=$1,level=$2,gold=$3,${attr}=${attr}+${attrInc},current_streak=$4,best_streak=$5,last_quest_date=$6,updated_at=NOW() WHERE id=$7`,[xp,level,gold,streak,best,today,req.userId]);await c.query('UPDATE quests SET completed=true,completed_at=NOW(),updated_at=NOW() WHERE id=$1',[q.id]);await c.query('INSERT INTO activity_log(user_id,type,message,xp_delta,gold_delta,metadata) VALUES($1,$2,$3,$4,$5,$6)',[req.userId,'QUEST_COMPLETED',`Completed quest: ${q.title}`,q.xp_reward,q.gold_reward,JSON.stringify({questId:q.id,leveled,level})]);const nu=await c.query('SELECT * FROM users WHERE id=$1',[req.userId]);return {user:publicUser(nu.rows[0]),quest:{...q,completed:true},leveled,newLevel:level};});res.json(result)}catch(e:any){res.status(e.status||400).json({message:e.message||'Could not complete quest'})}});
app.get('/api/inventory',auth,async(req,res)=>{const r=await pool.query('SELECT * FROM inventory WHERE user_id=$1 ORDER BY purchased_at DESC',[req.userId]);res.json({items:r.rows})});
const catalog=[{key:'focus-potion',type:'item',name:'Focus Potion',description:'A small reward for a focused day.',rarity:'Common',cost:50,emoji:'🧪'},{key:'xp-scroll',type:'item',name:'XP Scroll',description:'A scroll representing your next breakthrough.',rarity:'Rare',cost:75,emoji:'📜'},{key:'warrior-badge',type:'badge',name:'Warrior Badge',description:'For relentless action.',rarity:'Rare',cost:250,emoji:'🏆'},{key:'bookworm-badge',type:'badge',name:'Bookworm Badge',description:'Knowledge is power.',rarity:'Rare',cost:300,emoji:'📚'},{key:'early-bird-badge',type:'badge',name:'Early Bird Badge',description:'Rise before the world.',rarity:'Epic',cost:350,emoji:'🌅'},{key:'sage-badge',type:'badge',name:'Sage Badge',description:'Master of wisdom.',rarity:'Epic',cost:400,emoji:'🧙'},{key:'nightfall',type:'theme',name:'Nightfall Theme',description:'A darker journey.',rarity:'Common',cost:200,emoji:'🌌'},{key:'golden',type:'theme',name:'Golden Theme',description:'Shine brighter.',rarity:'Rare',cost:300,emoji:'✨'},{key:'celestial',type:'theme',name:'Celestial Theme',description:'Reach for the stars.',rarity:'Epic',cost:350,emoji:'🌠'},{key:'forest',type:'theme',name:'Forest Theme',description:'Nature within you.',rarity:'Rare',cost:275,emoji:'🌲'}];
app.get('/api/shop',auth,async(_,res)=>res.json({items:catalog}));
app.post('/api/shop/:key/buy',auth,async(req,res)=>{try{const item=catalog.find(x=>x.key===req.params.key);if(!item)return res.status(404).json({message:'Item not found'});const out=await tx(async c=>{const owned=await c.query('SELECT 1 FROM inventory WHERE user_id=$1 AND item_key=$2',[req.userId,item.key]);if(owned.rowCount)return Object.assign({},{already:true});const u=await c.query('SELECT * FROM users WHERE id=$1 FOR UPDATE',[req.userId]);if(u.rows[0].gold<item.cost)throw Object.assign(new Error('Not enough gold'),{status:400});await c.query('UPDATE users SET gold=gold-$1,theme=CASE WHEN $2=\'theme\' THEN $3 ELSE theme END WHERE id=$4',[item.cost,item.type,item.key,req.userId]);await c.query('INSERT INTO inventory(user_id,item_key,item_type,name,description,rarity) VALUES($1,$2,$3,$4,$5,$6)',[req.userId,item.key,item.type,item.name,item.description,item.rarity]);await c.query('INSERT INTO activity_log(user_id,type,message,gold_delta) VALUES($1,$2,$3,$4)',[req.userId,'SHOP_PURCHASE',`Purchased ${item.name}`,-item.cost]);const nu=await c.query('SELECT * FROM users WHERE id=$1',[req.userId]);return {user:publicUser(nu.rows[0]),item};});res.json(out)}catch(e:any){res.status(e.status||400).json({message:e.message||'Purchase failed'})}});
app.get('/api/progress',auth,async(req,res)=>{const u=(await pool.query('SELECT * FROM users WHERE id=$1',[req.userId])).rows[0];const q=await pool.query('SELECT * FROM quests WHERE user_id=$1',[req.userId]);const a=await pool.query("SELECT * FROM activity_log WHERE user_id=$1 ORDER BY created_at DESC LIMIT 10",[req.userId]);const completed=q.rows.filter(x=>x.completed);const week=Date.now()-7*86400000;const weekly=completed.filter(x=>new Date(x.completed_at||x.created_at).getTime()>=week).length;const earned=a.rows.reduce((n,x)=>n+Math.max(0,Number(x.gold_delta||0)),0);res.json({user:publicUser(u),completed:completed.length,weeklyCompleted:weekly,earnedGold:earned,recent:a.rows})});
const achievementDefs=[{key:'first-quest',name:'First Victory',description:'Complete your first quest.',target:1,icon:'quests',calc:(u,q,i)=>q.filter(x=>x.completed).length},{key:'quest-10',name:'Quest Hunter',description:'Complete 10 quests.',target:10,icon:'quests',calc:(u,q,i)=>q.filter(x=>x.completed).length},{key:'streak-7',name:'Flame Keeper',description:'Reach a 7-day streak.',target:7,icon:'streak',calc:(u,q,i)=>u.best_streak},{key:'level-5',name:'Rising Hero',description:'Reach level 5.',target:5,icon:'level',calc:(u,q,i)=>u.level},{key:'collector',name:'Collector',description:'Own 5 shop rewards.',target:5,icon:'inventory',calc:(u,q,i)=>i.length},{key:'gold-1000',name:'Gold Hoarder',description:'Accumulate 1,000 Gold.',target:1000,icon:'gold',calc:(u,q,i)=>u.gold}];
app.get('/api/achievements',auth,async(req,res)=>{const u=(await pool.query('SELECT * FROM users WHERE id=$1',[req.userId])).rows[0];const q=(await pool.query('SELECT * FROM quests WHERE user_id=$1',[req.userId])).rows;const i=(await pool.query('SELECT * FROM inventory WHERE user_id=$1',[req.userId])).rows;res.json({achievements:achievementDefs.map(a=>{const progress=Math.min(a.target,Number(a.calc(u,q,i)));return {...a,progress,unlocked:progress>=a.target}})})});
app.get('/api/leaderboard',auth,async(_,res)=>{const r=await pool.query(`SELECT id,name,level,xp,gold,current_streak FROM users ORDER BY level DESC,xp DESC,gold DESC LIMIT 50`);res.json({leaderboard:r.rows.map((u,i)=>({...u,rank:i+1,xp:Number(u.xp)}))})});
app.get('/api/profile',auth,async(req,res)=>{const u=await pool.query('SELECT * FROM users WHERE id=$1',[req.userId]);const a=await pool.query('SELECT * FROM activity_log WHERE user_id=$1 ORDER BY created_at DESC LIMIT 20',[req.userId]);res.json({user:publicUser(u.rows[0]),activity:a.rows})});
app.patch('/api/profile',auth,async(req,res)=>{const body=z.object({name:z.string().min(2).max(80).optional(),theme:z.string().max(40).optional()}).parse(req.body);const r=await pool.query('UPDATE users SET name=COALESCE($1,name),theme=COALESCE($2,theme),updated_at=NOW() WHERE id=$3 RETURNING *',[body.name,body.theme,req.userId]);res.json({user:publicUser(r.rows[0])})});

// ---------------- Marketplace / Payments ----------------
const physicalCatalog = [
  {key:'ascend-journal',name:'Ascend Productivity Journal',description:'A guided journal for quests, habits and weekly reflection.',price:399,stock:50,category:'Study',emoji:'📓',external_url:'https://www.amazon.in/s?k=productivity+journal'},
  {key:'study-kit',name:'Student Study Kit',description:'Stationery essentials for focused study sessions.',price:299,stock:100,category:'Study',emoji:'✏️',external_url:'https://www.amazon.in/s?k=student+stationery+kit'},
  {key:'water-bottle',name:'Motivation Water Bottle',description:'A reusable bottle for your daily routine.',price:499,stock:40,category:'Lifestyle',emoji:'🥤',external_url:'https://www.amazon.in/s?k=motivational+water+bottle'},
  {key:'ascend-backpack',name:'Student Backpack',description:'Everyday backpack for campus and your next adventure.',price:899,stock:25,category:'Lifestyle',emoji:'🎒',external_url:'https://www.amazon.in/s?k=student+backpack'}
];
const ensureCommerce=async()=>{
  await pool.query(`CREATE TABLE IF NOT EXISTS products (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), key VARCHAR(80) UNIQUE NOT NULL, name VARCHAR(160) NOT NULL, description TEXT DEFAULT '', price INT NOT NULL CHECK(price>=0), stock INT NOT NULL DEFAULT 0 CHECK(stock>=0), category VARCHAR(40) NOT NULL DEFAULT 'General', emoji VARCHAR(8) DEFAULT '📦', external_url TEXT, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
  CREATE TABLE IF NOT EXISTS orders (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, product_key VARCHAR(80) NOT NULL, product_name VARCHAR(160) NOT NULL, amount INT NOT NULL CHECK(amount>=0), gold_discount INT NOT NULL DEFAULT 0, final_amount INT NOT NULL CHECK(final_amount>=0), name VARCHAR(80) NOT NULL, phone VARCHAR(30) NOT NULL, address TEXT NOT NULL, city VARCHAR(80) NOT NULL, state VARCHAR(80) NOT NULL, pincode VARCHAR(12) NOT NULL, payment_status VARCHAR(30) NOT NULL DEFAULT 'PENDING', order_status VARCHAR(30) NOT NULL DEFAULT 'PLACED', razorpay_order_id VARCHAR(120), razorpay_payment_id VARCHAR(120), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
  CREATE INDEX IF NOT EXISTS idx_orders_user ON orders(user_id, created_at DESC);`);
  for(const x of physicalCatalog) await pool.query(`INSERT INTO products(key,name,description,price,stock,category,emoji,external_url) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(key) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,price=EXCLUDED.price,category=EXCLUDED.category,emoji=EXCLUDED.emoji,external_url=EXCLUDED.external_url`,[x.key,x.name,x.description,x.price,x.stock,x.category,x.emoji,x.external_url]);
};
app.get('/api/marketplace/products',auth,async(_,res)=>{const r=await pool.query('SELECT * FROM products WHERE active=true ORDER BY created_at');res.json({products:r.rows})});
app.get('/api/orders',auth,async(req,res)=>{const r=await pool.query('SELECT * FROM orders WHERE user_id=$1 ORDER BY created_at DESC',[req.userId]);res.json({orders:r.rows})});
const orderSchema=z.object({productKey:z.string().min(1),goldToUse:z.number().int().min(0).max(100000).default(0),name:z.string().min(2).max(80),phone:z.string().min(10).max(20),address:z.string().min(5).max(300),city:z.string().min(2).max(80),state:z.string().min(2).max(80),pincode:z.string().regex(/^\d{6}$/)});
app.post('/api/payments/create-order',auth,async(req,res)=>{try{const body=orderSchema.parse(req.body);const p=(await pool.query('SELECT * FROM products WHERE key=$1 AND active=true',[body.productKey])).rows[0];if(!p)return res.status(404).json({message:'Product not found'});if(p.stock<1)return res.status(400).json({message:'Product is out of stock'});const u=(await pool.query('SELECT * FROM users WHERE id=$1',[req.userId])).rows[0];const discount=Math.min(body.goldToUse,Number(u.gold),Math.floor(Number(p.price)*0.25));const final=Math.max(1,Number(p.price)-discount);const key=process.env.RAZORPAY_KEY_ID,secret=process.env.RAZORPAY_KEY_SECRET;if(!key||!secret)return res.status(503).json({message:'Payment gateway is not configured. Add RAZORPAY_KEY_ID and RAZORPAY_KEY_SECRET to server/.env'});const basic=Buffer.from(`${key}:${secret}`).toString('base64');const rr=await fetch('https://api.razorpay.com/v1/orders',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Basic ${basic}`},body:JSON.stringify({amount:final*100,currency:'INR',receipt:`ascend_${Date.now()}`})});if(!rr.ok){const t=await rr.text();console.error(t);return res.status(502).json({message:'Could not create payment order'});}const ro=await rr.json();const o=await pool.query(`INSERT INTO orders(user_id,product_key,product_name,amount,gold_discount,final_amount,name,phone,address,city,state,pincode,razorpay_order_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[req.userId,p.key,p.name,p.price,discount,final,body.name,body.phone,body.address,body.city,body.state,body.pincode,ro.id]);res.status(201).json({order:o.rows[0],razorpay:{id:ro.id,amount:ro.amount,currency:ro.currency,key}})}catch(e:any){console.error(e);res.status(400).json({message:e.message||'Invalid order data'})}});
app.post('/api/payments/verify',auth,async(req,res)=>{try{const {orderId,paymentId,signature}=z.object({orderId:z.string().uuid(),paymentId:z.string().min(3),signature:z.string().min(10)}).parse(req.body);const o=(await pool.query('SELECT * FROM orders WHERE id=$1 AND user_id=$2',[orderId,req.userId])).rows[0];if(!o)return res.status(404).json({message:'Order not found'});const secret=process.env.RAZORPAY_KEY_SECRET;if(!secret)return res.status(503).json({message:'Payment gateway is not configured'});const expected=(await import('node:crypto')).createHmac('sha256',secret).update(`${o.razorpay_order_id}|${paymentId}`).digest('hex');if(expected!==signature)return res.status(400).json({message:'Payment signature verification failed'});const out=await tx(async c=>{const locked=(await c.query('SELECT * FROM orders WHERE id=$1 FOR UPDATE',[orderId])).rows[0];if(locked.payment_status==='PAID')return locked;const u=(await c.query('SELECT gold FROM users WHERE id=$1 FOR UPDATE',[req.userId])).rows[0];if(Number(u.gold)<Number(locked.gold_discount))throw new Error('Not enough Gold for this discount');await c.query('UPDATE users SET gold=gold-$1,updated_at=NOW() WHERE id=$2',[locked.gold_discount,req.userId]);await c.query('UPDATE products SET stock=stock-1 WHERE key=$1 AND stock>0',[locked.product_key]);const updated=(await c.query(`UPDATE orders SET payment_status='PAID',order_status='PROCESSING',razorpay_payment_id=$1 WHERE id=$2 RETURNING *`,[paymentId,orderId])).rows[0];await c.query('INSERT INTO activity_log(user_id,type,message,gold_delta,metadata) VALUES($1,$2,$3,$4,$5)',[req.userId,'ORDER_PAID',`Paid for ${locked.product_name}`, -Number(locked.gold_discount),JSON.stringify({orderId})]);return updated;});res.json({order:out})}catch(e:any){console.error(e);res.status(400).json({message:e.message||'Payment verification failed'})}});
app.get('/api/payments/config',auth,async(_,res)=>res.json({configured:Boolean(process.env.RAZORPAY_KEY_ID&&process.env.RAZORPAY_KEY_SECRET),keyId:process.env.RAZORPAY_KEY_ID||null}));

app.use((_,res)=>res.status(404).json({message:'Route not found'})); ensureCommerce().then(()=>app.listen(port,()=>console.log(`Ascend API running on http://localhost:${port}`))).catch(e=>{console.error('Commerce setup failed',e);process.exit(1)});
